name: ${project.name}
version: ${project.version}
main: me.fishy246.easychatclear.Main
author: Fishy246

commands:
  chatclear:
    description: Allows the user to clear the global chat
    aliases: [cc,clearchat,chatclear,gcc,globalchatclear,clearglobalchat]
  individualchatclear:
    description: Allows the user to clear an individual players chat
    aliases: [playerchatclear,chatclearplayer,icc,pcc,ccp]
  easychatclear:
    description: The main ECC plugin command
    aliases: [ecc,easycc]